[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Form handling configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Security headers for forms
[[headers]]
  for = "/forms/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:;"

# Form processing configuration
[forms]
  [forms.contact-form]
    name = "Contact Form"
    honeypot = "bot-field"
    [forms.contact-form.fields]
      name = { required = true }
      email = { required = true, type = "email" }
      subject = { required = true }
      message = { required = true }
  
  [forms.test-contact-form]
    name = "Test Contact Form"
    honeypot = "bot-field"
    [forms.test-contact-form.fields]
      name = { required = true }
      email = { required = true, type = "email" }
      subject = { required = true }
      message = { required = true } 